<a href="https://colab.research.google.com/github/harry9855/PYTHON-AI-ML/blob/main/PandasPracSeries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#WHAT IS PANDAS

Pandas is a Python library used for:

handling structured data
analyzing datasets
cleaning messy data
working with tables like Excel/SQL

It is built on top of NumPy but is much more convenient for real-world data work.

#WHAT IS PANDAS SERIES

Pandas series is like a coloumn in table.It is 1-D array holding data of any type.

A Series is a 1-dimensional labeled array in pandas.

Think of it as:

a single column from a table
or an upgraded NumPy array with labels (indexes)

In [ ]:
import numpy as np
import pandas as pd

#SERIES

###Series from list

Series has basically two things 'indexes' which are genrated automatically and values which are given to it

In [ ]:
# String Series
country=["India", "USA", "China", "Russia", "Japan"]
pd.Series(country)
#It has dtype as object and 99% of times pandas says string as object

0     India
1       USA
2     China
3    Russia
4     Japan
dtype: object

In [ ]:
# Integr Series
runs=[98,88,75,93,52,71,38,12,43]
runs=pd.Series(runs)
# It has dtype as int64

In [ ]:
# Creating Custom Indexes
marks_list=[98,92,78,85,90]
subjects=["Social Sci","Maths","Englis","Science","Punjabi"]
pd.Series(marks_list,index=subjects)
# One thing length indexes and length values should match

Social Sci    98
Maths         92
Englis        78
Science       85
Punjabi       90
dtype: int64

In [ ]:
# setiing a name
marks=pd.Series(marks_list,index=subjects,name="Hardik Marks")
marks
# In pd.Series, the name parameter gives a name/title to the Series.
# marks created here is a object of series

Social Sci    98
Maths         92
Englis        78
Science       85
Punjabi       90
Name: Hardik Marks, dtype: int64

In [ ]:
print(marks)

Social Sci    98
Maths         92
Englis        78
Science       85
Punjabi       90
Name: Hardik Marks, dtype: int64

###Series from dict

In [ ]:
marks_dict={"Social Sci":98,"Maths":92,"Englis":78,"Science":85,"Punjabi":90}
pd.Series(marks_dict,name="Hardik Marks")
# using dicitionary helps to convert keys to indexes and values to values in series

Social Sci    98
Maths         92
Englis        78
Science       85
Punjabi       90
Name: Hardik Marks, dtype: int64

#SERIES ATTRIBUTES

In [ ]:
# As we know marks we created is a object of series that is why we can some of the attributes of the series in marks

In [ ]:
marks

Social Sci    98
Maths         92
Englis        78
Science       85
Punjabi       90
Name: Hardik Marks, dtype: int64

In [ ]:
#Size : Returns total number of elements.
marks.size

5

In [ ]:
#dtype : Returns datatype of elements.
marks.dtype

dtype('int64')

In [ ]:
#name : Returns Series name.
marks.name

'Hardik Marks'

In [ ]:
# is_unique : Checks whether all values are unique.
marks.is_unique

True

In [ ]:
# index : Returns index object.
marks.index

Index(['Social Sci', 'Maths', 'Englis', 'Science', 'Punjabi'], dtype='object')

In [ ]:
# values : Returns the N-D NumPy array of values
marks.values

array([98, 92, 78, 85, 90])

# Difference Between Series and DataFrame in Pandas

## Series

### Definition
A Series is a 1-dimensional labeled array in Pandas.

It stores:
- Single column of data
- Index + Values
```
Think :
Single column of data
```
---

## Data frame
### Definition
A DataFrame is a 2-dimensional labeled table
```
Think:
Rows + Columns (like Excel sheet)
```
It contains:
- rows
- columns

A column inside DataFrame is actually a Series

#Series using read CSV

In [ ]:
# pd.read_csv reads the dataset in default format of data frame not series
subs=pd.read_csv("/content/subs.csv")
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [ ]:
print(type(subs))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
# To convert data frame to series we use a function called squeeze
subs=subs.squeeze()

In [ ]:
print(type(subs))

<class 'pandas.core.series.Series'>

In [ ]:
vk=(pd.read_csv("/content/kohli_ipl.csv",index_col="match_no")).squeeze()

In [ ]:
vk

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [ ]:
movies=(pd.read_csv("/content/bollywood.csv",index_col="movie")).squeeze()
movies

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

###SERIES METHOD

In [ ]:
# Head and tail
subs.head()
# head shows top 5 element from series

0    48
1    57
2    40
3    43
4    44
Name: Subscribers gained, dtype: int64

In [ ]:
subs.tail()
# tail show bottom 5 elemts from series

360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, dtype: int64

In [ ]:
vk.head(3)
# it also shows customs number of elemts from top

match_no
1     1
2    23
3    13
Name: runs, dtype: int64

In [ ]:
vk.tail(2)
# similarly it also show custom number of elements from bottom

match_no
214    25
215     7
Name: runs, dtype: int64

In [ ]:
# Sample : it randomly shows 1 row from the series
movies.sample()

movie
Bullett Raja    Saif Ali Khan
Name: lead, dtype: object

In [ ]:
# in sample we can also provide the number of samples we required
movies.sample(5)

movie
Vaada (film)              Arjun Rampal
Oh My God (2008 film)     Vinay Pathak
Running Shaadi              Arsh Bajwa
The Journey of Karma     Shakti Kapoor
Flat 211                    Jayesh Raj
Name: lead, dtype: object

# value_counts()

`value_counts()` is used to count the frequency of unique values in a Series.

It tells:
- how many times each value appears

In [ ]:
movies.value_counts()

lead
Akshay Kumar         48
Amitabh Bachchan     45
Ajay Devgn           38
Salman Khan          31
Sanjay Dutt          26
                     ..
Seema Azmi            1
Akanksha Puri         1
Charanpreet Insan     1
Jaideep Ahlawat       1
Monali Thakur         1
Name: count, Length: 566, dtype: int64

In [ ]:
# sort_values() :- is used to sort data in ascending or descending (but to that we need ascending=False , it is a hidden parameter in sort_values func)
# It is not a permanent change in series it is inplace
# To make changes in orignal we need to do inplace=True
# vk.sort_values(inplace=True)
vk.sort_values()

match_no
8        0
87       0
93       0
91       0
206      0
      ...
164    100
120    100
123    108
126    109
128    113
Name: runs, Length: 215, dtype: int64

In [ ]:
vk.sort_values(ascending=False)

match_no
128    113
126    109
123    108
120    100
164    100
      ...
93       0
130      0
206      0
207      0
211      0
Name: runs, Length: 215, dtype: int64

In [ ]:
# similarly we can sort index also using function sort index
movies.sort_index(inplace=True)
# we have made inplace true that means changes will permanent in movies series

In [ ]:
movies

movie
1920 (film)                   Rajniesh Duggall
1920: London                     Sharman Joshi
1920: The Evil Returns             Vicky Ahuja
1971 (2007 film)                Manoj Bajpayee
2 States (2014 film)              Arjun Kapoor
                                   ...
Zindagi 50-50                      Veena Malik
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi Tere Naam           Mithun Chakraborty
Zokkomon                       Darsheel Safary
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Name: lead, Length: 1500, dtype: object

# MATHEMATICAL METHODS IN SERIES

some of the most used function are :

- `count()` : is used to count number of values in sereis similar to size function but one difference that count does not include null (NaN) values. It ignores missing values.

In [ ]:
vk.count()

np.int64(215)

- `sum() and product()`: It find sum and product the values in the series

In [ ]:
subs.sum()

np.int64(49510)

In [ ]:
subs.product()
# answer is zero because it has any one element zero in the series

np.int64(0)

- `mean()` : Mean is the average of all values.

```text
Mean = Sum of all values / Total number of values

In [ ]:
print(vk.mean())
# it gives average run scored by virat kolhi

30.855813953488372

- `median()` is used to find the middle value of data after sorting. It automatically ignores NaN values.


```text
for odd values
Median = ((n + 1) / 2)th value
for even value
Median = Average of middle two values

In [ ]:
vk.median()

24.0

- `mode()` is used to find the most frequently occurring value in data. The value with highest frequency is called Mode.

In [ ]:
vk.mode()

0    0
Name: runs, dtype: int64

- `std()` is used to calculate the Standard Deviation of data.

    Standard Deviation measures: how spread out values are from the mean
    
---

```text
σ = √( Σ(x - μ)² / N )

σ = standard deviation
x = each value
μ = mean
N = total number of values

In [ ]:
subs.std()

62.67502303725269

`var()` is used to calculate the Variance of data.

Variance measures:
- how far data values are spread from the mean

---



```text
σ² = Σ(x - μ)² / N

Where:

σ² = population variance
x = each value
μ = population mean
N = total number of observations

In [ ]:
subs.var()

3928.1585127201556

`min()/max()` function are used to calculate minimum and maximum value in dataset

In [ ]:
subs.min()

33

In [ ]:
subs.max()

396

In [ ]:
# describe() it is a function used to describe some mathematical methods
subs.describe()

count    365.000000
mean     135.643836
std       62.675023
min       33.000000
25%       88.000000
50%      123.000000
75%      177.000000
max      396.000000
Name: Subscribers gained, dtype: float64

#SEREIS INDEXING

In [ ]:
x=pd.Series([20,10,11,15,25,30,34,38,94,68])

INDEXING

In [ ]:
# Positive Indexing
print(x[0])
print(x[3])
print(x[1])

20
15
10

In [ ]:
movies # in this series movie name is index and lead is value therefore to do indexing in movie series we use movie name
# but internally it also provide numeric indexing also from 0 , in movie series i can nuse umbers and movie name both for indexing

movie
1920 (film)                   Rajniesh Duggall
1920: London                     Sharman Joshi
1920: The Evil Returns             Vicky Ahuja
1971 (2007 film)                Manoj Bajpayee
2 States (2014 film)              Arjun Kapoor
                                   ...
Zindagi 50-50                      Veena Malik
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi Tere Naam           Mithun Chakraborty
Zokkomon                       Darsheel Safary
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Name: lead, Length: 1500, dtype: object

In [ ]:
# negative indexing
#print(x[-1])
# negative indexing always gives error it does not work in pandas
# negative only work custom indexes that also custom index must be 'string'
print(movies[-1])

Meghan Jadhav

/tmp/ipykernel_2619/400177056.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(movies[-1])

In [ ]:
print(movies[0])
print(movies["Zindagi Tere Naam"])
# warning is getting shown for movies[0] because it is allowing now but it is depricated
# in future movies[0] here '0' will be taken as label not position that means
# as i have written movies["Zindagi Tere Naam"] similarly movies[0] will search for 0 in index not 0 th position
# numeric index only works as position for custom indexes that also custom index must be 'string' otherwise it will work as label

Rajniesh Duggall
Mithun Chakraborty

/tmp/ipykernel_2619/651007082.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(movies[0])

#SLICING
it works same way as in python

In [ ]:
vk[5:16]

match_no
6      9
7     34
8      0
9     21
10     3
11    10
12    38
13     3
14    11
15    50
16     2
Name: runs, dtype: int64

In [ ]:
vk[-5:]

match_no
211     0
212    20
213    73
214    25
215     7
Name: runs, dtype: int64

#EDITING SERIES

In [ ]:
marks

Social Sci    98
Maths         92
Englis        78
Science       85
Punjabi       90
Name: Hardik Marks, dtype: int64

In [ ]:
# editing using indexing
marks[1]=100
marks

/tmp/ipykernel_2619/1295684579.py:2: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  marks[1]=100

Social Sci     98
Maths         100
Englis         78
Science        85
Punjabi        90
Name: Hardik Marks, dtype: int64

In [ ]:
# editing if index does not exist
marks["Social Studies"]=98
marks # it will create new coloumn of social studies in table

Social Sci         98
Maths             100
Englis             78
Science            85
Punjabi            90
Social Studies     98
Name: Hardik Marks, dtype: int64

In [ ]:
# editing using slicing
runs[2:4]=[100,101]
runs

0     98
1     88
2    100
3    101
4     52
5     71
6     38
7     12
8     43
dtype: int64

# SERIES ALSO HAVE PYTHON FUNCTIONALITIES

In [ ]:
print(len(subs))

365

In [ ]:
print(type(subs)) # it disply the datatype of the particular csv file

<class 'pandas.core.series.Series'>

In [ ]:
print(dir(subs)) # it display the functionaliteis present that we can use

['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__bool__', '__class__', '__column_consortium_standard__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append', '_arith_method', '_as_manager', '_attrs', '_binop', '_cacher', '_can_hold_na', '_check_inplace_and_allows_duplicate_labels', '_check_is_chained_assignment_possible', '_check_label_or_level_ambiguity', '_check_setitem_copy', '_clear_item_cache', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_expanddim', '_constructor_expanddim_from_mgr', '_constructor_from_mgr', '_data', '_deprecate_downcast', '_dir_additions', '_dir_deletions', '_drop_axis', '_drop_labels_or_levels', '_duplicated', '_find_valid_index', '_flags', '_flex_method', '_from_mgr', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cacher', '_get_cleaned_column_resolvers', '_get_index_resolvers', '_get_label_or_level_values', '_get_numeric_data', '_get_rows_with_mask', '_get_value', '_get_values_tuple', '_get_with', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_init_dict', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_cached', '_is_copy', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_is_view', '_is_view_after_cow_rules', '_item_cache', '_ixs', '_logical_func', '_logical_method', '_map_values', '_maybe_update_cacher', '_memory_usage', '_metadata', '_mgr', '_min_count_stat_function', '_name', '_needs_reindex_multi', '_pad_or_backfill', '_protect_consolidate', '_reduce', '_references', '_reindex_axes', '_reindex_indexer', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_single', '_repr_data_resource_', '_repr_latex_', '_reset_cache', '_reset_cacher', '_set_as_cached', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_is_copy', '_set_labels', '_set_name', '_set_value', '_set_values', '_set_with', '_set_with_engine', '_shift_with_freq', '_slice', '_stat_function', '_stat_function_ddof', '_take_with_is_copy', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'argmax', 'argmin', 'argsort', 'array', 'asfreq', 'asof', 'astype', 'at', 'at_time', 'attrs', 'autocorr', 'axes', 'backfill', 'between', 'between_time', 'bfill', 'bool', 'case_when', 'clip', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'divmod', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtype', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'ewm', 'expanding', 'explode', 'factorize', 'ffill', 'fillna', 'filter', 'first', 'first_valid_index', 'flags', 'floordiv', 'ge', 'get', 'groupby', 'gt', 'hasnans', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'interpolate', 'is_monotonic_decreasing', 'is_monotonic_increasing', 'is_unique', 'isin', 'isna', 'isnull', 'item', 'items', 'keys', 'kurt', 'kurtosis', 'last', 'last_valid_index', 'le', 'list', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'memory_usage', 'min', 'mod', 'mode', 'mul', 'multiply', 'name', 'nbytes', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pad', 'pct_change', 'pipe', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'radd', 'rank', 'ravel', 'rdiv', 'rdivmod', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'repeat', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'searchsorted', 'sem', 'set_axis', 'set_flags', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'std', 'struct', 'sub', 'subtract', 'sum', 'swapaxes', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_frame', 'to_hdf', 'to_json', 'to_latex', 'to_list', 'to_markdown', 'to_numpy', 'to_period', 'to_pickle', 'to_sql', 'to_string', 'to_timestamp', 'to_xarray', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unique', 'unstack', 'update', 'value_counts', 'values', 'var', 'view', 'where', 'xs']

In [ ]:
print(sorted(subs)) # print sorted subs inside list

[33, 33, 35, 37, 39, 40, 40, 40, 40, 42, 42, 43, 44, 44, 44, 45, 46, 46, 48, 49, 49, 49, 49, 50, 50, 50, 51, 54, 56, 56, 56, 56, 57, 61, 62, 64, 65, 65, 66, 66, 66, 66, 67, 68, 70, 70, 70, 71, 71, 72, 72, 72, 72, 72, 73, 74, 74, 75, 76, 76, 76, 76, 77, 77, 78, 78, 78, 79, 79, 80, 80, 80, 81, 81, 82, 82, 83, 83, 83, 84, 84, 84, 85, 86, 86, 86, 87, 87, 87, 87, 88, 88, 88, 88, 88, 89, 89, 89, 90, 90, 90, 90, 91, 92, 92, 92, 93, 93, 93, 93, 95, 95, 96, 96, 96, 96, 97, 97, 98, 98, 99, 99, 100, 100, 100, 101, 101, 101, 102, 102, 103, 103, 104, 104, 104, 105, 105, 105, 105, 105, 105, 105, 105, 105, 108, 108, 108, 108, 108, 108, 109, 109, 110, 110, 110, 111, 111, 112, 113, 113, 113, 114, 114, 114, 114, 115, 115, 115, 115, 117, 117, 117, 118, 118, 119, 119, 119, 119, 120, 122, 123, 123, 123, 123, 123, 124, 125, 126, 127, 128, 128, 129, 130, 131, 131, 132, 132, 134, 134, 134, 135, 135, 136, 136, 136, 137, 138, 138, 138, 139, 140, 144, 145, 146, 146, 146, 146, 147, 149, 150, 150, 150, 150, 151, 152, 152, 152, 153, 153, 153, 154, 154, 154, 155, 155, 156, 156, 156, 156, 157, 157, 157, 157, 158, 158, 159, 159, 160, 160, 160, 160, 162, 164, 166, 167, 167, 168, 170, 170, 170, 170, 171, 172, 172, 173, 173, 173, 174, 174, 175, 175, 176, 176, 177, 178, 179, 179, 180, 180, 180, 182, 183, 183, 183, 184, 184, 184, 185, 185, 185, 185, 186, 186, 186, 188, 189, 190, 190, 192, 192, 192, 196, 196, 196, 197, 197, 202, 202, 202, 203, 204, 206, 207, 209, 210, 210, 211, 212, 213, 214, 216, 219, 220, 221, 221, 222, 222, 224, 225, 225, 226, 227, 228, 229, 230, 231, 233, 236, 236, 237, 241, 243, 244, 245, 247, 249, 254, 254, 258, 259, 259, 261, 261, 265, 267, 268, 269, 276, 276, 290, 295, 301, 306, 312, 396]

In [ ]:
print(min(subs))

33

In [ ]:
print(max(subs))

396

In [ ]:
list(marks) # convert marks series to list(datatype conversion)

[98, 100, 78, 85, 90, 98]

In [ ]:
"2 States (2014 film)" in movies # Also have membership Operator like(in,is etc)

True

In [ ]:
for i in movies.index: # looping also works in series(like for ,while etc)
  print(i)

1920 (film)
1920: London
1920: The Evil Returns
1971 (2007 film)
2 States (2014 film)
22 Yards
3 A.M. (2014 film)
3 Deewarein
3 Idiots
3 Storeys
31st October (film)
36 China Town
3G (film)
404 (film)
5 Weddings
68 Pages
7 Hours to Go
7 Khoon Maaf
7½ Phere
88 Antop Hill
99 (2009 film)
99.9 FM (film)
?: A Question Mark
A Decent Arrangement
A Flat (film)
A Flying Jatt
A Gentleman
ABCD 2
Aa Dekhen Zara
Aa Gaya Hero
Aabra Ka Daabra
Aag (2007 film)
Aagey Se Right
Aaj Ka Andha Kanoon
Aaja Nachle
Aakhari Decision
Aakrosh (2010 film)
Aalaap (film)
Aan: Men at Work
Aanch
Aankhen (2002 film)
Aap Kaa Surroor
Aap Ki Khatir (2006 film)
Aapko Pehle Bhi Kahin Dekha Hai
Aarakshan
Aashayein
Aashiq Banaya Aapne
Aashiqui 2
Aashiqui.in
Aasma: The Sky Is the Limit
Aazaan
Ab Tak Chhappan 2
Ab Tumhare Hawale Watan Saathiyo
Accident on Hill Road
Acid Factory
Action Jackson (2014 film)
Action Replayy
Adharm (2006 film)
Ae Dil Hai Mushkil
Aetbaar
Agent Vinod (2012 film)
Aggar (film)
Agneepath (2012 film)
Agnipankh
Ahista Ahista (2006 film)
Airlift (film)
Aisa Kyon Hota Hai?
Aisa Yeh Jahaan
Aitraaz
Aiyaary
Aiyyaa
Ajab Gazabb Love
Ajab Prem Ki Ghazab Kahani
Ajji
Akaash Vani
Aksar
Aksar 2
Aladin (film)
Alag
Albert Pinto Ko Gussa Kyun Aata Hai?
Aligarh (film)
All Is Well (2015 film)
All the Best: Fun Begins
Allah Ke Banday
Alone (2015 Hindi film)
Aloo Chaat (film)
Always Kabhi Kabhi
Amavas
Amit Sahni Ki List
Anaarkali of Aarah
Anamika (2008 film)
Andaaz
Andaaz
Andhadhun
Angel (2011 film)
Anjaana Anjaani
Anjaane (2005 film)
Ankahee (2006 film)
Ankhon Dekhi
Ankur Arora Murder Case
Anna (2016 film)
Antardwand
Anthony Kaun Hai?
Anuradha (2014 film)
Anwar (2007 film)
Apaharan
Apartment (film)
Apna Asmaan
Apna Sapna Money Money
Apne
Arjun Patiala
Arjun: The Warrior Prince
Armaan (2003 film)
Article 15 (film)
Aryan: Unbreakable
Asambhav
Ata Pata Laapata
Aur Pappu Paas Ho Gaya
Aurangzeb (film)
Aval (2017 film)
Awara Paagal Deewana
Awarapan
Azhar (film)
B.A. Pass
Baabarr
Baabul (2006 film)
Baaghi (2016 film)
Baaghi 2
Baar Baar Dekho
Baat Bann Gayi
Baaz: A Bird in Danger
Baazaar
Babloo Happy Hai
Babuji Ek Ticket Bambai
Babumoshai Bandookbaaz
Baby (2015 Hindi film)
Bachche Kachche Sachche
Bachke Rehna Re Baba
Bachna Ae Haseeno
Badhaai Ho
Badla (2019 film)
Badlapur (film)
Badlapur Boys
Badmashiyaan
Badrinath Ki Dulhania
Baghban (2003 film)
Bajatey Raho
Bajirao Mastani
Bajrangi Bhaijaan
Bala (2019 film)
Balwinder Singh Famous Ho Gaya
Banaras (2006 film)
Band Baaja Baaraat
Bandook
Bang Bang!
Bangistan
Banjo (2016 film)
Bank Chor
Barah Aana
Bardaasht
Bareilly Ki Barfi
Barfi!
Barkhaa
Barsaat (2005 film)
Bas Ek Pal
Basti (film)
Batla House
Battalion 609
Batti Gul Meter Chalu
Bazaar E Husn
Bbuddah... Hoga Terra Baap
Befikre
Begum Jaan
Behen Hogi Teri
Beiimaan Love
Being Cyrus
Bewafaa (2005 film)
Bewakoofiyaan
Beyond the Clouds (2017 film)
Bezubaan Ishq
Bhaag Johnny
Bhaag Milkha Bhaag
Bhagam Bhag
Bhagmati (2005 film)
Bhaiaji Superhit
Bhanwarey
Bhavesh Joshi Superhero
Bheja Fry (film)
Bheja Fry 2
Bhola in Bollywood
Bhool Bhulaiyaa
Bhoomi (film)
Bhoot (film)
Bhoot Returns
Bhoot Unkle
Bhoothnath
Bhoothnath Returns
Bhopal: A Prayer for Rain
Bhram
Big Brother (2007 film)
Billu
Bin Bulaye Baraati
Bioscopewala
Bittoo Boss
Black (2005 film)
Black Friday (2007 film)
Blackmail (2005 film)
Blood Brothers (2007 Indian film)
Blood Money (2012 film)
Bloody Isshq
Blue (2009 film)
Bluffmaster!
Bobby Jasoos
Bodyguard (2011 Hindi film)
Bol Bachchan
Bollywood Diaries
Bombairiya
Bombay Talkies (film)
Bombay Velvet
Bombay to Bangkok
Bombay to Goa (2007 film)
Boom (film)
Border (1997 film)
Boss (2013 Hindi film)
Brahman Naman
Break Ke Baad
Breakaway (2011 film)
Brij Mohan Amar Rahe
Brothers (2015 film)
Bubble Gum (film)
Buddha Mar Gaya
Buddha in a Traffic Jam
Bullet: Ek Dhamaka
Bullett Raja
Bumboo
Bumm Bumm Bole
Bumper Draw
Bunty Aur Babli
Bypass Road (film)
C Kkompany
Calapor (film)
Calcutta Mail
Calendar Girls (2015 film)
Cash (2007 film)
Chaahat – Ek Nasha
Chaalis Chauraasi
Chaar Din Ki Chandni
Chaarfutiya Chhokare
Chak De! India
Chakravyuh (2012 film)
Chal Chala Chal
Chal Pichchur Banate Hain
Chalk n Duster
Challo Driver
Chalo Dilli
Chalte Chalte (2003 film)
Chameli (film)
Chamku
Chance Pe Dance
Chand Ke Paar Chalo (film)
Chand Sa Roshan Chehra
Chandni Chowk to China
Charas (2004 film)
Chargesheet (film)
Chase (2010 film)
Chashme Baddoor (2013 film)
Chatur Singh Two Star
Cheeni Kum
Chef (2017 film)
Chehraa
Chennai Express
Chetna: The Excitement
Chhodon Naa Yaar
Chhota Bheem and the Throne of Bali
Chicken Curry Law
Children of Heaven
Children of War (2014 film)
Chillar Party
Chinar Daastaan-E-Ishq
Chingaari
Chintu Ji
Chittagong (film)
Chocolate (2005 film)
Chor Chor Super Chor
Chori Chori (2003 film)
Chup Chup Ke
Chura Liyaa Hai Tumne
Cigarette Ki Tarah
City of Gold (2010 film)
CityLights (2014 film)
Classic – Dance of Love
Click (2010 film)
Cocktail (2012 film)
Coffee Bloom
Coffee with D
Commando 3 (film)
Commando: A One Man Army
Company (film)
Contract (2008 film)
Corporate (2006 film)
Court (film)
Crazy Cukkad Family
Creature 3D
Crook (film)
D (film)
D-Day (2013 film)
Daas Dev
Daawat-e-Ishq
Dabangg
Dabangg 2
Dabangg 3
Daddy (2017 film)
Daddy Cool (2009 Hindi film)
Damadamm!
Dangal (film)
Dangerous Ishhq
Darling (2007 Indian film)
Darna Mana Hai
Darna Zaroori Hai
Darr @ the Mall
Darwaaza Bandh Rakho
Dassehra
Dasvidaniya
Days of Tafree
De Dana Dan
De De Pyaar De
De Taali
Deadline: Sirf 24 Ghante
Dear Dad (film)
Dear Friend Hitler
Dear Maya
Dear Zindagi
Dedh Ishqiya
Deewaar (2004 film)
Deewane Huye Paagal
Dehraadun Diary
Dekh Tamasha Dekh
Delhi Belly (film)
Delhi Safari
Delhi-6
Department (film)
Deshdrohi
Desi Boyz
Desi Kattey
Detective Byomkesh Bakshy!
Dev (2004 film)
Devaki (2005 film)
Devdas (2002 Hindi film)
Devi (2016 film)
Dhadak
Dhamaal
Dhanak
Dharam Sankat Mein
Dharm (film)
Dharti Kahe Pukar Ke (2006 film)
Dhobi Ghat (film)
Dhokha
Dhol (film)
Dhoom
Dhoom 2
Dhoom 3
Dhoondte Reh Jaaoge
Dhoop
Dhund (2003 film)
Dil Bechara
Dil Bechara Pyaar Ka Maara
Dil Bole Hadippa!
Dil Dhadakne Do
Dil Diya Hai
Dil Dosti Etc
Dil Jo Bhi Kahey...
Dil Jo Na Keh Saka
Dil Juunglee
Dil Ka Rishta
Dil Kabaddi
Dil Maange More
Dil Ne Jise Apna Kahaa
Dil Pardesi Ho Gayaa
Dil Toh Baccha Hai Ji
Dil Toh Deewana Hai
Dilliwali Zaalim Girlfriend
Dilwale (2015 film)
Direct Ishq
Dirty Politics (film)
Dishkiyaoon
Dishoom
Do Dooni Chaar
Do Lafzon Ki Kahani (film)
Dobaara: See Your Evil
Dobara
Dolly Ki Doli
Don (2006 Hindi film)
Don 2
Don Muthu Swami
Don't Stop Dreaming
Dongari Ka Raja
Dor (film)
Dostana (2008 film)
Dosti: Friends Forever
Double Cross (2005 film)
Double Dhamaal
Dream Girl (2019 film)
Dreams (2006 film)
Drishyam (2015 film)
Drona (2008 film)
Dude Where's the Party?
Dulha Mil Gaya
Dum (2003 Hindi film)
Dum Laga Ke Haisha
Dum Maaro Dum (film)
Dunno Y... Na Jaane Kyon
Dus
Dus Kahaniyaan
Eight: The Power of Shani
Ek Ajnabee
Ek Alag Mausam
Ek Aur Ek Gyarah
Ek Chalis Ki Last Local
Ek Din 24 Ghante
Ek Haseena Thi Ek Deewana Tha
Ek Hasina Thi (film)
Ek Kahani Julie Ki
Ek Khiladi Ek Haseena (film)
Ek Main Aur Ekk Tu
Ek Paheli Leela
Ek Se Badhkar Ek (2004 film)
Ek Se Bure Do
Ek Second... Jo Zindagi Badal De?
Ek Tha Tiger
Ek Thi Daayan
Ek Thi Rani Aisi Bhi
Ek Villain
Ek Vivaah... Aisa Bhi
Ek: The Power of One
Ekk Deewana Tha
Ekkees Toppon Ki Salaami
Eklavya: The Royal Guard
Elaan (2005 film)
Enemmy
English Vinglish
Entertainment (2014 film)
Escape from Taliban
Evening Shadows
F.A.L.T.U
Family (2006 film)
Family of Thakurganj
Familywala
Fan (film)
Fanaa (2006 film)
Fareb (2005 film)
Fashion (2008 film)
Fatso!
Ferrari Ki Sawaari
Fever (2016 film)
Fida
Fight Club – Members Only
Filmistaan
Finding Fanny
Firaaq
Firangi
Fitoor
Flat 211
Flavors (film)
Fool & Final
Footpath (2003 film)
Force (2011 film)
Force 2
Fox (film)
Fraud Saiyaan
Freaky Ali
Fredrick (film)
From Sydney with Love
Fruit and Nut (film)
FryDay
Fuddu
Fugly (film)
Fukrey
Fukrey Returns
Fun – Can Be Dangerous Sometimes
Fun2shh... Dudes in the 10th Century
G Kutta Se
Gabbar Is Back
Gabbar Is Back
Gali Guleiyan
Game (2011 film)
Gandhi My Father
Gang of Ghosts
Gangaajal
Gangoobai
Gangs of Wasseypur
Gangs of Wasseypur – Part 2
Gangster (2006 film)
Garam Masala (2005 film)
Garv: Pride & Honour
Gattu
Gauri: The Unborn
Gayab
Genius (2018 Hindi film)
Ghajini (2008 film)
Ghanchakkar (film)
Ghayal: Once Again
Ghost (2012 film)
Ghost (2019 film)
Gippi
Girlfriend (2004 film)
Global Baba
Go (2007 film)
Go Goa Gone
Goal (2007 Hindi film)
God Tussi Great Ho
Gold (2018 film)
Goliyon Ki Raasleela Ram-Leela
Gollu Aur Pappu
Golmaal Again
Golmaal Returns
Golmaal: Fun Unlimited
Gone Kesh
Good Boy Bad Boy
Good Newwz
Gori Tere Pyaar Mein
Gour Hari Dastaan
Grand Masti
Great Grand Masti
Green Card Fever
Guddu Ki Gun
Guddu Rangeela
Guest iin London
Gulaab Gang
Gulaal (film)
Gulabi Gang (film)
Gully Boy
Gumnaam – The Mystery
Gunday
Guru (2007 film)
Guzaarish (film)
Haal-e-Dil
Haasil
Hai Apna Dil Toh Awara
Haider (film)
Half Girlfriend (film)
Halkaa
Halla Bol
Hamari Adhuri Kahani
Hamid (film)
Hanuman (2005 film)
Happy Bhag Jayegi
Happy Ending (film)
Happy Husbands (2011 film)
Happy New Year (2014 film)
Happy Phirr Bhag Jayegi
Haraamkhor
Hari Puttar: A Comedy of Terrors
Hasee Toh Phasee
Haseena Parkar
Hastey Hastey
Hate Story
Hate Story 2
Hate Story 4
Hattrick (film)
Hatya (2004 film)
Haunted – 3D
Hava Aney Dey
Hawa (film)
Hawaa Hawaai
Hawaizaada
Hawas (2004 film)
Hawayein
Hazaaron Khwaishein Aisi
Heartless (2014 film)
Helicopter Eela
Hello (2008 film)
Hello Darling
Help (film)
Hero (2015 Hindi film)
Heroes (2008 film)
Heroine (2012 film)
Heropanti
Hey Bro
Heyy Babyy
Hichki
High Jack (film)
Highway (2014 Hindi film)
Himmatwala (2013 film)
Hind Ka Napak Ko Jawab: MSG Lion Heart 2
Hindi Medium
Hisss
Holiday (2006 film)
Holiday: A Soldier Is Never Off Duty
Home Delivery
Honeymoon Travels Pvt. Ltd.
Honour Killing (film)
Hope Aur Hum
Horror Story (film)
Hostel (2011 film)
Hotel Salvation
Housefull (2010 film)
Housefull 2
Housefull 4
Hulchul (2004 film)
Hum Chaar
Hum Hai Raahi Car Ke
Hum Tum
Hum Tum Aur Ghost
Hum Tum Shabana
Hum Tumhare Hain Sanam
Hume Tumse Pyaar Kitna
Humko Deewana Kar Gaye
Humko Tumse Pyaar Hai
Humne Jeena Seekh Liya
Humpty Sharma Ki Dulhania
Humshakals
Hungama (2003 film)
Hunterrr
Hyderabad Blues 2
I Am (2010 Indian film)
I Am Kalam
I Hate Luv Storys
I Love Desi
I Love NY (2015 film)
I Proud to Be an Indian
I See You (2006 film)
Impatient Vivek
India's Most Wanted (film)
Indian Babu
Indu Sarkar
Inkaar (2013 film)
Insaaf: The Justice
Insan
Inteha (2003 film)
Inteqam: The Perfect Game
Iqbal (film)
Iqraar by Chance
Irada (2017 film)
Irudhi Suttru
Ishaqzaade
Ishkq in Paris
Ishq Click
Ishq Forever
Ishq Hai Tumse
Ishq Ke Parindey
Ishq Vishk
Ishqedarriyaan
Ishqeria
Ishqiya
Isi Life Mein
Island City (2015 film)
Issaq
It's a Wonderful Afterlife
JD (film)
Jaal: The Trap
Jaan-E-Mann
Jaane Hoga Kya
Jaane Kahan Se Aayi Hai
Jaane Kyun De Yaaron
Jab Harry Met Sejal
Jab Tak Hai Jaan
Jab We Met
Jabariya Jodi
Jack and Dil
Jackpot (2013 film)
Jagga Jasoos
Jahan Jaaeyega Hamen Paaeyega
Jai Chiranjeeva
Jai Gangaajal
Jai Ho (film)
Jai Jawaan Jai Kisaan (film)
Jai Veeru
Jail (2009 film)
Jajantaram Mamantaram
Jal (film)
Jalebi (film)
Jalpari: The Desert Mermaid
James (2005 film)
Janasheen
Jannat (film)
Jattu Engineer
Jawani Diwani: A Youthful Joyride
Jayantabhai Ki Luv Story
Jazbaa
Jeena Hai Toh Thok Daal
Jeena Isi Ka Naam Hai (film)
Jhalki
Jhankaar Beats
Jhoom Barabar Jhoom
Jhootha Hi Sahi
Jhootha Kahin Ka
Jia Aur Jia
Jigariyaa
Jigyaasa
Jimmy (2008 film)
Jism (2003 film)
Jo Bole So Nihaal (film)
Jo Hum Chahein
Jodhaa Akbar
Jodi Breakers
Joggers' Park (film)
John Day (film)
Johnny Gaddaar
Joker (2012 film)
Jolly LLB
Judgementall Hai Kya
Judwaa 2
Jugni (2016 film)
Julie (2004 film)
Julie 2
Junglee (2019 film)
Junooniyat
Jurm (2005 film)
Just Married (2007 film)
Kaabil
Kaagaz Ke Fools
Kaal (2005 film)
Kaalakaandi
Kaalo
Kaanchi: The Unbreakable
Kaante
Kaashi in Search of Ganga
Kabhi Alvida Naa Kehna
Kabir Singh
Kabul Express
Kadvi Hawa
Kagaar: Life on the Edge
Kahaani
Kahin Hai Mera Pyar
Kai Po Che!
Kaise Kahoon Ke... Pyaar Hai
Kal Ho Naa Ho
Kalank
Kalyug (2005 film)
Kaminey
Kapoor & Sons
Karam (film)
Karar: The Deal
Karle Pyaar Karle
Karma Aur Holi
Karthik Calling Karthik
Karwaan
Karzzzz
Kasak (2005 film)
Kash Aap Hamare Hote
Katti Batti
Kaun Hai Jo Sapno Mein Aaya
Kaun Kitne Paani Mein
Keep Safe Distance (film)
Kesari (film)
Khajoor Pe Atke
Khakee
Khamosh Pani
Khamoshh... Khauff Ki Raat
Khamoshi (2019 film)
Khamoshiyan
Khap (film)
Khatta Meetha (2010 film)
Khel Toh Ab Shuru Hoga
Khel – No Ordinary Game
Khichdi: The Movie
Khoobsurat (2014 film)
Khosla Ka Ghosla
Khoya Khoya Chand
Khuda Kasam
Khushi (2003 Hindi film)
Khwaabb
Khwahish
Ki & Ka
Kick (2014 film)
Kill Dil
Kis Kis Ki Kismat
Kis Kisko Pyaar Karoon
Kisaan
Kismat (2004 film)
Kismat Konnection
Kismat Love Paisa Dilli
Kisna: The Warrior Poet
Kisse Pyaar Karoon
Kites (film)
Knock Out (2010 film)
Koi Aap Sa
Koi Mere Dil Mein Hai
Koi... Mil Gaya
Koyelaanchal
Krazzy 4
Krishna Aur Kans
Krishna Cottage
Krrish
Kucch Luv Jaisaa
Kucch To Hai
Kuch Kuch Locha Hai
Kuch Naa Kaho
Kuchh Bheege Alfaaz
Kuchh Meetha Ho Jaye
Kudiyon Ka Hai Zamana
Kuku Mathur Ki Jhand Ho Gayi
Kurbaan (2009 film)
Kushti (film)
Kya Dilli Kya Lahore
Kya Love Story Hai
Kyaa Kool Hai Hum
Kyaa Kool Hain Hum 3
Kyaa Super Kool Hain Hum
Kyon Ki
Kyun! Ho Gaya Na...
LOC Kargil
Laaga Chunari Mein Daag
Laal Rang
Ladies vs Ricky Bahl
Lafangey Parindey
Lage Raho Munna Bhai
Lahore (film)
Laila Majnu (2018 film)
Lakeer – Forbidden Lines
Lakshmi (2014 film)
Lakshya (film)
Lamhaa
Lekar Hum Deewana Dil
Life Express (2010 film)
Life Is Beautiful (2014 film)
Life Ki Toh Lag Gayi
Life Mein Kabhie Kabhiee
Life Partner
Life in a... Metro
Lipstick Under My Burkha
Listen... Amaya
Little Zizou
Login (film)
Loins of Punjab Presents
London Dreams
Lootera
Love Aaj Kal
Love Breakups Zindagi
Love Games (film)
Love Ke Chakkar Mein
Love Sex Aur Dhokha
Love Shagun
Love Sonia
Love Story 2050
Love U...Mr. Kalakaar!
Love in Bombay
Love per Square Foot
Loveshhuda
Luck (2009 film)
Luck by Chance
Luckhnowi Ishq
Lucknow Central
Lucky Kabootar
Lucky: No Time for Love
Luv U Alia
Luv U Soniyo
M Cream
M.S. Dhoni: The Untold Story
MP3: Mera Pehla Pehla Pyaar
MSG-2 The Messenger
MSG: The Messenger
MSG: The Warrior Lion Heart
Maan Gaye Mughal-e-Azam
Maatr
Maazii
Machhli Jal Ki Rani Hai
Machine (2017 film)
Mad About Dance
Madaari
Made in China (2019 film)
Madhoshi
Madras Cafe
Magic Magic 3D
Mai (2013 film)
Main Aisa Hi Hoon
Main Aur Mr. Riight
Main Aurr Mrs Khanna
Main Hoon Na
Main Hoon Part-Time Killer
Main Krishna Hoon
Main Madhuri Dixit Banna Chahti Hoon
Main Meri Patni Aur Woh
Main Prem Ki Diwani Hoon
Main Tera Hero
Maine Gandhi Ko Nahin Mara
Maine Pyaar Kyun Kiya?
Malamaal Weekly
Malik Ek
Mangal Pandey: The Rising
Manikarnika: The Queen of Jhansi
Manjhi – The Mountain Man
Manjunath (film)
Manmarziyaan
Manorama Six Feet Under
Manto (2018 film)
Mantra (2016 film)
Maqbool
Mard Ko Dard Nahi Hota
Mardaani
Mardaani 2
Margarita with a Straw
Marigold (2007 film)
Marjaavaan
Market (2003 film)
Married 2 America
Mary Kom (film)
Masaan
Masti (2004 film)
Mastizaade
Mastram
Matru Ki Bijlee Ka Mandola
Matrubhoomi
Mausam (2011 film)
Maximum (film)
Meenaxi: A Tale of Three Cities
Meerabai Not Out
Meeruthiya Gangsters
Meinu Ek Ladki Chaahiye
Memories in March
Mercury (film)
Mere Baap Pehle Aap
Mere Brother Ki Dulhan
Mere Dad Ki Maruti
Mere Dost Picture Abhi Baki Hai
Mere Genie Uncle
Mere Jeevan Saathi (2006 film)
Mere Pyare Prime Minister
Meri Biwi Ka Jawaab Nahin
Meri Pyaari Bindu
Mickey Virus
Milenge Milenge
Miley Naa Miley Hum
Mirch
Mirzya (film)
Miss Tanakpur Haazir Ho
Missing (2018 film)
Mission Istaanbul
Mission Mangal
Mitron
Mittal v/s Mittal
Moh Maya Money
Mohalla Assi
Mohenjo Daro (film)
Mom (film)
Money Hai Toh Honey Hai
Monica (film)
Monsoon Shootout
Morning Raga
Motichoor Chaknachoor
Motu Patlu: King of Kings
Mr Prime Minister
Mr. Bhatti on Chutti
Mr. Singh Mrs. Mehta
Mr. X (2015 film)
Mubarakan
Mughal-e-Azam
Mujhse Fraaandship Karoge
Mujhse Shaadi Karogi
Mukhbiir
Mukkabaaz
Mulk (film)
Mumbai 125 KM
Mumbai Can Dance Saala
Mumbai Delhi Mumbai
Mumbai Mast Kallander
Mumbai Matinee
Mumbai Meri Jaan
Mumbai Salsa
Mumbai Se Aaya Mera Dost
Mumbhai Connection
Mummy Punjabi
Munna Bhai M.B.B.S.
Munna Michael
Murari the Mad Gentleman
Murder (2004 film)
Murder 2
Murder 3
Musafir (2004 film)
Muskaan
My Birthday Song
My Bollywood Bride
My Brother…Nikhil
My Friend Pinto
My Name Is Khan
My Wife's Murder
NH-8 Road to Nidhivan
NH10 (film)
Na Ghar Ke Na Ghaat Ke
Naach (2004 film)
Naam Shabana
Naina (2005 film)
Naksha
Namaste England
Namastey London
Nanhe Jaisalmer
Nanu Ki Jaanu
Naqaab
Nasha (film)
Naughty @ 40
Nautanki Saala!
Nawabzaade
Nayee Padosan
Neal 'n' Nikki
Neerja
Nehlle Pe Dehlla
Netaji Subhas Chandra Bose: The Forgotten Hero
New York (2009 film)
Newton (film)
Nil Battey Sannata
Nirdosh
Nishabd
No Entry
No One Killed Jessica
No Problem (2010 film)
No Smoking (2007 film)
Noor (film)
Not a Love Story (2011 film)
Notebook (2019 film)
Nothing but Life
O Teri
OMG – Oh My God!
October (2018 film)
Oh My God (2008 film)
Ok Jaanu
Om (2003 film)
Om Shanti Om
Om-Dar-B-Dar
Omerta (film)
Omkara (2006 film)
Once Upon a Time in Mumbaai
Once Upon ay Time in Mumbai Dobaara!
One Day: Justice Delivered
One Two Three
One by Two (2014 film)
Out of Control (2003 film)
Oye Lucky! Lucky Oye!
P Se PM Tak
P Se Pyaar F Se Faraar
PK (film)
PM Narendra Modi
Paa (film)
Paan Singh Tomar (film)
Paanch Ghantey Mien Paanch Crore
Paap
Paathshaala
Padmaavat
Padmashree Laloo Prasad Yadav
Pagalpanti (2019 film)
Page 3 (film)
Paheli
Paisa Vasool
Pal Pal Dil Ke Paas
Paltan (film)
Panchlait
Pankh
Paranthe Wali Gali
Parched
Parineeta (2005 film)
Parmanu: The Story of Pokhran
Partner (2007 film)
Parwana (2003 film)
Pataakha
Patel Ki Punjabi Shaadi
Pati Patni Aur Woh (2019 film)
Patiala House (film)
Paying Guests
Peepli Live
Pehchaan: The Face of Truth
Phamous
Phantom (2015 film)
Phas Gaye Re Obama
Phata Poster Nikhla Hero
Phhir
Phillauri (film)
Phir Hera Pheri
Phir Kabhi
Phir Milenge
Phobia (2016 film)
Phoonk 2
Photograph (film)
Pihu
Piku
Pinjar (film)
Pink (2016 film)
Pizza (2014 film)
Plan (film)
Players (2012 film)
Police Force: An Inside Story
Policegiri
Popcorn Khao! Mast Ho Jao
Poster Boys
Praan Jaye Par Shaan Na Jaye
Prague (2013 film)
Pranaam
Prassthanam
Prateeksha
Prem Kaa Game
Prem Ratan Dhan Payo
Prince (2010 film)
Purani Jeans
Pyaar Impossible!
Pyaar Ka Punchnama
Pyaar Ka Punchnama 2
Pyaar Ke Side Effects
Pyaar Mein Twist
Pyare Mohan
Qaidi Band
Qarib Qarib Singlle
Qayamat: City Under Threat
Qissa (film)
Queen (2014 film)
Quick Gun Murugun
Ra.One
Raabta (film)
Raag Desh (film)
Raanjhanaa
Raat Gayi Baat Gayi?
Raavan
Raaz (2002 film)
Raaz: Reboot
Raaz: The Mystery Continues
Raazi
Rab Ne Bana Di Jodi
Race (2008 film)
Race 2
Race 3
Raees (film)
Raghu Romeo
Ragini MMS
Ragini MMS 2
Rahasya
Raid (2018 film)
Raincoat (film)
Raja Bhaiya (film)
Raja Natwarlal
Rajjo
Rajma Chawal
Rakht
Rakhtbeej
Ramaa: The Saviour
Ramaiya Vastavaiya
Raman Raghav 2.0
Ramayana: The Epic
Ramji Londonwaley
Ramprasad Ki Tehrvi
Ranbanka
Ranchi Diaries
Rang De Basanti
Rang Rasiya
Rangoon (2017 Hindi film)
Rangrezz
Rann (film)
Raqeeb
Rascals (2011 film)
Rebellious Flower
Red Alert: The War Within
Red Swastik
Red: The Dark Side
Revati (film)
Revolver Rani
Ribbon (film)
Right Here Right Now (film)
Right Yaaa Wrong
Risk (2007 film)
Risknamaa
Riyasat (film)
Road to Sangam
Roadside Romeo
Roar: Tigers of the Sundarbans
Rock On 2
Rock On!!
Rocket Singh: Salesman of the Year
Rockstar (2011 film)
Rocky Handsome
Rog
Rok Sako To Rok Lo
Rokkk
Rough Book
Roy (film)
Rudraksh (film)
Rukh (film)
Rules: Pyaar Ka Superhit Formula
Run (2004 film)
Running Shaadi
Rush (2012 film)
Rustom (film)
Saaho
Saand Ki Aankh
Saankal
Saansein
Saare Jahaan Se Mehnga
Saas Bahu Aur Sensex
Saat Uchakkey
Saathiya (film)
Saawan... The Love Season
Saawariya
Saaya (2003 film)
Sabki Bajegi Band
Sachin: A Billion Dreams

In [ ]:
100-marks # all airthmetic operation also works

Social Sci         2
Maths              0
Englis            22
Science           15
Punjabi           10
Social Studies     2
Name: Hardik Marks, dtype: int64

In [ ]:
vk>=50 # relational operator also works on the series

match_no
1      False
2      False
3      False
4      False
5      False
       ...
211    False
212    False
213     True
214    False
215    False
Name: runs, Length: 215, dtype: bool